export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST';
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS';
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL';

export const BRAND_ADD_REQUEST = 'BRAND_ADD_REQUEST';
export const BRAND_ADD_SUCCESS = 'BRAND_ADD_SUCCESS';
export const BRAND_ADD_FAIL = 'BRAND_ADD_FAIL';

export const BRAND_EDIT_REQUEST = 'BRAND_EDIT_REQUEST';
export const BRAND_EDIT_SUCCESS = 'BRAND_EDIT_SUCCESS';
export const BRAND_EDIT_FAIL = 'BRAND_EDIT_FAIL';

export const BRAND_OFFERS_ADD_REQUEST = 'BRAND_OFFERS_ADD_REQUEST';
export const BRAND_OFFERS_ADD_SUCCESS = 'BRAND_OFFERS_ADD_SUCCESS';
export const BRAND_OFFERS_ADD_FAIL = 'BRAND_OFFERS_ADD_FAIL';

export const BRAND_OFFERS_DELETE_REQUEST = 'BRAND_OFFERS_DELETE_REQUEST';
export const BRAND_OFFERS_DELETE_SUCCESS = 'BRAND_OFFERS_DELETE_SUCCESS';
export const BRAND_OFFERS_DELETE_FAIL = 'BRAND_OFFERS_DELETE_FAIL';