export const PRODUCT_LIST_REQUESTS = "PRODUCT_LIST_REQUESTS";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUESTS = "PRODUCT_DETAILS_REQUESTS";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const REMOVE_PRODUCT_DETAILS = "REMOVE_PRODUCT_DETAILS";