export const WISHLIST_REQUESTS = 'WISHLIST_REQUESTS';
export const WISHLIST_SUCCESS = 'WISHLIST_SUCCESSS';
export const WISHLIST_FAIL = 'WISHLIST_FAIL';
export const WISHLIST_RESET = 'WISHLIST_RESET';
